palette = "mocha"

[palettes.everblush]
background = "#141b1e"
lighter_background = "#232a2d"
red = "#e57474"
green = "#8ccf7e"
yellow = "#e5c76b"
blue = "#67b0e8"
magenta = "#c47fd5"
cyan = "#6cbfbf"
light_gray = "#b3b9b8"
foreground = "#dadada"


[palettes.mocha]
background = "#1e1e2e"
lighter_background = "#313244"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#94e2d5"
light_gray = "#a6adc8"
foreground = "#cdd6f4"

# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€Î»](bold fg:blue)"
error_symbol = " [ï•“](bold fg:red)"

# Third param
[directory]
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "fg:blue"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "../"

[git_branch]
format = "[ï•” ](fg:foreground)[$symbol$branch ]($style)"
symbol = "ï˜ "
style = "bold magenta"

[git_status]
format ='([\[$all_status$ahead_behind\] ]($style))'
conflicted = "="
ahead =	"[ ï¢ $count ](fg:green)"
behind = "[ ï£ $count ](fg:red)"
diverged = "â‡•ï¢ ${ahead_count}ï£ ${behind_count}"
untracked = "[ ?$count ](fg:cyan)"
modified = "[ ï„ª$count ](fg:green)"
staged = "[ ï§$count ](fg:cyan)"
renamed = "[ Â»$count ](fg:magenta)"
deleted = "[ âœ˜$count ](fg:red)"
disabled = false
style = "fg:foreground"

[cmd_duration]
disabled = true

[docker_context]
disabled=true
symbol = "ïŒˆ "

[dotnet]
symbol = 'ğŸ¥… '
style = 'green'
heuristic = false

[conda]
disabled=true
symbol = "ï„Œ "

[dart]
disabled=true
symbol = "î˜ "

[package]
disabled=true
symbol = "ï£– "

[perl]
disabled=true
symbol = "î© "

[php]
disabled=true
symbol = "î˜ˆ "

[ruby]
disabled=true
symbol = "îˆ¾ "

[java]
disabled=true
symbol = "îœ¸ "

[lua]
disabled=false
symbol = "î˜  "
style = "bold blue"

[nodejs]
disabled=false

[swift]
disabled=true
symbol = "ï¯£ "

[julia]
disabled=true
format = "[$symbol$version]($style) "
symbol = "à®ƒ "
style = "bold green"

[python]
disabled=false
# format = 'via [${symbol}${pyenv_prefix}${version}( $virtualenv)]($style) '
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "î˜† "
style = "italic bold yellow"

[rust]
disabled=false
format = "on [$symbol$version]($style) "
# style = "bold green"

[cmake]
disabled = false
format = "via [$symbol($version )]($style)"
style = "bold red"

